services:
  backend:
    build:
      context: ../Captioner-backend
    environment:
      BACKEND_PASSWORD: "${BACKEND_PASSWORD}"
      DROPBOX_APP_KEY: "${DROPBOX_APP_KEY}"  # no default, fail if unset
      DROPBOX_APP_SECRET: "${DROPBOX_APP_SECRET}"
      DROPBOX_REFRESH_TOKEN: "${DROPBOX_REFRESH_TOKEN}"
      DROPBOX_ROOT_PATH: "${DROPBOX_ROOT_PATH}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
    ports:
      - "8000:8000"
    volumes:
      - ../Captioner-backend/app:/app/app  # live code reload
    restart: on-failure  # restart container on failure
    working_dir: /app  # set working directory for uvicorn
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # For local development inject env vars via .env or IDE run configs; no env_file in compose
    # For production, inject via orchestrator or CI/CD

# When you build the frontend server, you can add it here as another service.
# For example:
#  frontend:
#    build:
#      context: ../Captioner-frontend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend
